### ISSUE TITLE
Which APIs and Modules could be implemented?

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#2]
Hallo, 

first of all : awesome work! :D 
I just was thinking APIs could be used for numpy (so which classes and methods)?
And I was asking what modules should be also implemented?

- numpy
- scipy
- pandas
- matplotlib

Is there a way to generate a List with APIs on every module? 
So could check which APIs exist in python and which should be implemented. 

Moreover I think this libs could be used very well in F# and Powershell. 
At end : great work for starting ;)

**Comment by dotChris90** [comment]
@Oceania2018 @fdncred  by the way. the side https://xtensor.readthedocs.io/en/latest/numpy.html also delivers a good overview / List about important APIs we should focus.

**Comment by Oceania2018** [comment]
@dotChris90 It's time to start with our pandas repo.
`pandas is built on top of NumPy and is intended to integrate well within a scientific computing environment with many other 3rd party libraries.`

**Comment by dotChris90** [comment]
Wow great idea. But the name I am not sure which fits well.

Pandas.NET I find sounds better. Unfortunately we can not do a word game here like numpy and NumSharp.

Candas. For C# analystics and data frames does not sound sooo fantastic.

So I guess pandas.net is best at moment. :)

**Comment by dotChris90** [comment]
An other question.

When implementing pandas we will face troubles with methods parameter. Most method will accept numpy arrays and normal lists. Since we are not duck type but strong data types we should accept interfaces.

So final question. Shall we NDArray implement IList, IEnumerable?

**Comment by Oceania2018** [comment]
@fdncred Any idea about the new repo for python pandas?

**Comment by Oceania2018** [comment]
@dotChris90 We can overload API in different data type as much as possible.

**Comment by fdncred** [comment]
@Oceania2018 I haven't used pandas. I'll have to see what it does.

@dotChris90 See below of an example of listing all apis in a module, numpy in this example.  [Link](http://code.activestate.com/recipes/553262-list-classes-methods-and-functions-in-a-module/) where I found this.

I'm not sure if this is what you're looking for. Of course, the script could be tweaked to show what you want.
[numpy.txt](https://github.com/Oceania2018/NumSharp/files/2545969/numpy.txt)

**Comment by dotChris90** [comment]
@fdncred thanks. Yeah before was looking for this. But now more thinking we should develop according issues or use cases. Most importantly.

But thanks for sharing :)

**Comment by dotChris90** [comment]
I will close this because I guess it is better to be issue driven. ;)
