### ISSUE TITLE
implement numpy Matrix Class

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#27]
following the API doc https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matrix.html

**Comment by botsharp2018** [comment]
```
Note

It is no longer recommended to use this class, even for linear algebra. 
Instead use regular arrays. 
The class may be removed in the future.
```

**Comment by dotChris90** [comment]
okay understood. Just one question in general here. 

In Python there is the possibility to create an array of lists containing doubles for a matrix. Also there is the possibility to create array of arrays. For sure the array of array strategy brings a better performance when using matrix operations.

In C# we would have possibility of NDArray of NArrays of doubles or NDArray of usual double array.
I am very sure, that NDArray of NDArray will lead to some performance issues since NDArray is an adapter class of a true array. But in case of NDArray<double[]> we could get full performance support. 

So final question : shouldn't we design NumSharp in a way that we avoid nested NDArrays?

**Comment by Oceania2018** [comment]
We should consider performance first. Let's make a big change, like separate  NDArray<T> as 1 dim array, NDArray2<T> as 2 dim array, and fore T as value type.
```
if(!(typeof(T).equals(typeof(int32))) && !(typeof(T).equals(typeof(decimal))))
```

**Comment by Oceania2018** [comment]
Please retire the Matrix class. If you insist to keep it, I suggest that `Matrix` inherits `NDArray<T>`, just keep `Shape = new List<int>() {0, 0}`, the only different is `Shape` property. I reopen this issue till @dotChris90  fix it. Thanks.

**Comment by dotChris90** [comment]
Agree

**Comment by dotChris90** [comment]
Merged. Only inv I removed because reimplement in ndarray.

**Comment by dotChris90** [comment]
remove because matrix now inheritage from NDArray
