### ISSUE TITLE
Unique() and Random() methods do not resolve

### ISSUE THREAD

**Issue by frank-ozgul** [Oceania2018/NumSharp#3]
Have they not been implemented yet?

**Comment by Oceania2018** [comment]
@frank-ozgul  It's all implemented.

## Unique()
`var nClasses = y.Unique().Length;`

## Random()
![image](https://user-images.githubusercontent.com/1705364/46920923-9ece7f80-cfba-11e8-98e7-7a0af25f8eb9.png)

I'm using NumSharp in the Neural Network implementation, check this [repo](https://github.com/Oceania2018/Bigtree.MachineLearning)

**Comment by frank-ozgul** [comment]
I was using the package  at NuGet Site. So it does not seem to have them. But I notice now in the github code they exist. Thank you.
