### ISSUE TITLE
Generic ARange?

### ISSUE THREAD

**Issue by fdncred** [Oceania2018/NumSharp#37]
Is there a reason why the ARange isn't generic?

```cs
public static NDArray<T> ARange<T>(this NDArray<T> np, int stop, int start = 0, int step = 1) where T : IConvertible
{
    int index = 0;

    np.Data = Enumerable.Range(start, stop - start)
                        .Where(x => index++ % step == 0)
                        .Select(x => (T)Convert.ChangeType(x, typeof(T)))
                        .ToArray();
    return np;
}
```

**Comment by Oceania2018** [comment]
10 times performance slower when you using `(T)Convert.ChangeType(x, typeof(T))`. I've tested it yesterday.

**Comment by dotChris90** [comment]
But would it be possible to cast the whole array?

Don't have a laptop at moment in front lol so can't test.

Sth like

(T[]) Enumerable....

The cast is than at one object not every element.

**Comment by fdncred** [comment]
@Oceania2018 Wow. Must be the boxing/unboxing perf problems that I've read about.

@dotChris90 Here's a couple ways to cast [arrays ](https://stackoverflow.com/questions/2068120/c-sharp-cast-entire-array)- i haven't tried any of them.
