### ISSUE TITLE
Is there a reason to implement methods as extended methods?

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#4]
Hello again, 

just a question - no complain. :)
Is there a reason to implement methods as extension methods for NumSharp?

My consideration is just the following : 

- extensions methods is sth. C# connected 
- extensions methods are hard to use in other languages (e.g. powershell, F#. python.NET, ...)
- NumSharp could be used by many other languages if they are normal methods ;) 

thanks again for your time. ;)

**Comment by dotChris90** [comment]
Honestly - not 100% sure how is the current state. 

But remember in past I had following situations : 

- MATLAB ignores them completly (their NET.AddAssembly method or how it was called)
- Python.NET can not directly invoke too 
- Powershell can not use direct but! use them like normal functions like [FullClassPath]::ExtMethod()
- same to F#  

In general it is possible but you have to use them like normal functions. ;) 
But not sure how is current state with .NET Core.

**Comment by dotChris90** [comment]
But I got your point and agree. 

The Numpy libraries can be huge and its impressive that python people really do not split them into multiple files. 

Partial would be a good option since NumSharp shall follow the interfaces (APIs) of Numpy and this means the APIs are already chosen. 

I think extensions methods should be used to extend legacy code **or!** to extend classes of other libraries and make users feel comfortable with the classes (like in ASP.NET Core where the side packages like Entity framework core or so extends the main classes from ASP.NET Core).

**Comment by Oceania2018** [comment]
Yes, agree with you, I'll make some change. @dotChris90 Why not join this project? you know you have given some great ideas.

**Comment by dotChris90** [comment]
Thanks - would be a honour. ;)
If you want - I can do the restructure from extension methods to partial class methods since I suggested it. 
Already did a fork.
But will do in next days - unfortunately weekend already over here in Europe ;)

**Comment by Oceania2018** [comment]
Welcome to do a pull request.

**Comment by dotChris90** [comment]
Hmmm today tried rewriting the extensions methods to true methods ... 
the benefit of extension methods are : you can extend just some subset of all generics but do not have to implement method for all. 

When rewrote ARange noticed it. With extension methods we can say "implement it for NdArray<int> or NdArray<double>" but as true method have to think about NdArray<TData> with TData can be anything. I ended up into parts with "dynamic" keyword which looks quite messy .... 

Maybe first keep them extensions methods as long as found better way or until find way to implement subset of generic types. But will keep issue for traceability.

**Comment by Oceania2018** [comment]
I changed NdArray to NDArray

**Comment by dotChris90** [comment]
Honestly I wish there is something like INumeric Interface for numeric types. 

But after googling around and read some posts like "https://blogs.msdn.microsoft.com/lucabol/2009/02/05/simulating-inumeric-with-dynamic-in-c-4-0/" think it is not easy to find a performance efficient way. 

If there exist you could even limit the generics in NDArray to numeric types and it would be easy to bring the extension methods to true methods but anyway - maybe keep them first like they are and focus on extending the APIs.

**Comment by Oceania2018** [comment]
@dotChris90 Could you please help implement the [numpy.convolve](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.convolve.html). The [issue](https://github.com/Oceania2018/NumSharp/issues/6) is created #6

**Comment by dotChris90** [comment]
ok - will look for it today.

**Comment by dotChris90** [comment]
@Oceania2018 could you make a branch for this issue 4? I already have a branch for issue 4 on my fork and changed 5 methods from extensions methods to true methods. The tests still run and all working. F# and Powershell have no problems to find the methods and so you can execute them like in C#. I want to make pull request for issue 4 (which shall be pulled **not** to the master branch) and let you execute the tests on your PC - so can be sure all worked fine. :D or we even now think about some CI Servers to run unit Tests after every push and pull requests.

**Comment by Oceania2018** [comment]
@dotChris90 Don't need branch. Just pull request once your unit test passed, Not a lot of people are using this library currently.

**Comment by Oceania2018** [comment]
I've never used F#, and I'm curious how to invoke C# code in Powershell.
