### ISSUE TITLE
Span<T> and Slice?

### ISSUE THREAD

**Issue by fdncred** [Oceania2018/NumSharp#43]
@Oceania2018, @dotChris90 Have you seen Span<T>? It's as fast as C++ code in dotnet. It may be useful in this assembly.

Docs
https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.1
https://msdn.microsoft.com/en-us/magazine/mt814808.aspx
https://blogs.msdn.microsoft.com/mazhou/2018/03/25/c-7-series-part-10-spant-and-universal-memory-management/
https://adamsitnik.com/Span/

**Comment by Oceania2018** [comment]
Only can be used in .NET Core 2.1, NumSharp is using .net standard 2.0. We will change TargetFrameworks if needed.
https://www.codemag.com/article/1807051/Introducing-.NET-Core-2.1-Flagship-Types-Span-T-and-Memory-T

**Comment by dotChris90** [comment]
@Oceania2018 @fdncred  just for curiosity. Do u use at moment  . NET CORE or Full?
I think at moment we 3 are the main workers at this repo and I really like the span if we e.g. Slice arrays or generate different views for the same arrays. I think it could be also great when parallel operations.

**Comment by fdncred** [comment]
I used dotnet full i.e. net472 however, if we're going to make a numpy clone that as fast as the real numpy the only way to do it is either with p/invoke or span. I think the netstandard, full, and core are slowly merging into one framework. The future is definitely core. Even WinForms and Xaml/Wpf are being rewritten in dotnet core right now. It's scheduled for 3.0 release.

This bit of code was made me think of Span. The Skip and Take specifically.
https://github.com/Oceania2018/NumSharp/blob/4bbca14e07066aa4692c8df27dae0a097bdfb215/src/NumSharp/NdArray.cs#L109

The downside to dotnet core is that it brings a lot of baggage with it in the form of dozens of assemblies/dlls.

For now I would suggest doing something like this:
```cs
#if FULL
// do dotnet full stuff
#else
// do dotnet core stuff
#endif
```

**Comment by fdncred** [comment]
One other benefit with dotnet core is that it runs on Windows/Mac/Linux. It's designed to be cross-platform.

**Comment by dotChris90** [comment]
Totally agree. Honestly at moment try our code on windows 10 and a Linux MX (Debian base). It's simple awesome to see we can target multiple platforms.

And we targeting multiple languages. C#, F#, VB and I often try powershell.

Beside this there is the cool project peachpie which bring php to the dotnet world.

On top of this. There exist bindings for Matlab and python. We could use NumSharp in python lol

So it's cool time to be dotnet developer. 

But I guess soon or later there will be a new dotnet standard and with this we get the span in all frameworks.

:)

**Comment by dotChris90** [comment]
@Oceania2018 I agree 100% that we need the Span and I see that the slicing and views could give us the best benefits than :D Means we slicing matrix to multiple vectors (as an example) and do operations on vectors - the matrix could be also updated if we using this nice "managed pointers" :D

**Comment by dotChris90** [comment]
@fdncred @Oceania2018 did you hear something like a NetStadard2.1 or 3.0? 
The last Update I hear is that 2.0 is the latest standard. 
If we know a new standard we could plan if changing the Standard can be done now, in some weeks or .... other date

**Comment by fdncred** [comment]
@dotChris90, @Oceania2018 Before moving forward with Span<T> could you please test my latest push d1bed102119f861fece8309714afe9b3f7695109? I've only been able to test with my MacBook and OSX. Tomorrow I should be able to get back on Visual Studio. I just want confirmation that you can build all and run all the tests and they all succeed.

This is from vscode on my mac.
![screen shot 2018-11-04 at 2 10 20 pm](https://user-images.githubusercontent.com/343840/47969324-7971e600-e03b-11e8-8145-ae6a492f0e9e.PNG)

**Comment by dotChris90** [comment]
@fdncred mine works fine. First it shows such red lines like on the image. But after build, test and restart all works fine. Idk why .... but as long as it works. all ok. but at moment just on Windows 10. Maybe tomorrow should try it again on Linux.

**Comment by fdncred** [comment]
@dotChris90 are you using vscode or Visual Studio on Win10?

**Comment by dotChris90** [comment]
@fdncred VS Code. Honestly spoken now got used to it and like it more lol. Except on razor stuff... In cshtml stuff it still need some little more improvement

**Comment by fdncred** [comment]
Committed first Span<T> code with 01e2de198c687dec6cae3fdaaa10473cab627ca8. Ideally NDArray's ```T[] Data``` would be a ```Span<T> Data``` but it's not allowed. So, we'll have to figure out how and where to use it best.  It's benefit is speed and reduced memory allocations.

**Comment by dotChris90** [comment]
Ok glade to see everybody of us seems to agree go with 2.1 core lol.

OK cool to see there are first push with it👍

**Comment by fdncred** [comment]
If we're going to use Span<T> I don't think there is any other choice. I don't think netstandard nor netfull support Span<T>.

**Comment by Oceania2018** [comment]
Hooray

**Comment by fdncred** [comment]
@dotChris90  Is it released yet? or do you know when it will be released?

**Comment by dotChris90** [comment]
hm did not find any concrete date and on https://github.com/dotnet/standard/milestone/3 it seems there still some progress. I am not sure when it will be released. But I am sure it is not yet released. :(

**Comment by dotChris90** [comment]
Yes this is correct. But I say - Oceania2018 already changed the csproj - so all work. So it is not critical to change to 2.1 standard. ;) anyway - the first day it is released, we should change the csproj. ;)

**Comment by Oceania2018** [comment]
![image](https://user-images.githubusercontent.com/1705364/56852503-e75be380-68e1-11e9-9228-60b22af2193d.png)
