### ISSUE TITLE
Implement method ones

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#45]
implement numpys ones method following https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ones.html?highlight=ones#numpy.ones

**Comment by dotChris90** [comment]
Ok - will do.

**Comment by dotChris90** [comment]
Already done and merged. Will close this issue.

**Comment by Oceania2018** [comment]
Moved to creation folder, and make it as NumPy extension, because `numpy.ones` is belong to NumPy, not `NDArray`.
