### ISSUE TITLE
Check matrix multiplication again with index check 

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#48]
I think I was wrong about the indexing with matrix multiplication. Will check this tomorrow.

Seems when mapping 1 dimension to 2 dimension the columns are 1st dimension. I did the multiplication with lines first. I need to check this again.

Until now just checked the computed values.

**Comment by dotChris90** [comment]
I will do this

**Comment by Oceania2018** [comment]
Use `np.Vector(n, m)` to get the new `NDArray<T>` vector, and `np[n, m]` to get data value. Have tried to combine the index accessor, but failed.

**Comment by Oceania2018** [comment]
Don't worry about the performance, have already optimized for index accessor, cached index in variable `dimOffset`.
```
private int GetIndexInShape(params int[] select)
{
  int idx = 0;
  for (int i = 0; i < select.Length; i++)
  {
  	idx += dimOffset[i] * select[i];
  }

  return idx;
}
```

**Comment by dotChris90** [comment]
done.
