### ISSUE TITLE
Project structure with "src" & "test" folder

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#5]
Sorry again to disturb ^^' 

since C# is compiler and not interpreter project - shouldn't we make the structure : 

- "/src/NumSharp" instead of NumSharp 
- "/test/NumSharp.Test" instead of NumSharp.UnitTest

and for future (maybe one day ^^ ) have even "/src/SciSharp" and "/src/PandasSharp" ;)

**Comment by Oceania2018** [comment]
Agree with you, but the NumSharp.Test, I keep the name NumSharp.UnitTest.

![image](https://user-images.githubusercontent.com/1705364/46921279-1a323000-cfbf-11e8-9563-260e62656e50.png)

**Comment by dotChris90** [comment]
Ok. Perfect. Close this issue because already done ;)
