### ISSUE TITLE
Question : can a package be published to ~/.nuget on local machine? 

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#59]
Very stupid question.

Is it possible in msbuild to pack NumSharp after build automaticly and move to ~/.nuget?

I come up with this question because if there are other projects like pandas.net or I can image SciSharp and they are in different repos, we can not reference them in csproj. Because everybody of us has a different folder structure.

To avoid bad style or complains I think we have now 2 possible options.

No 1) one repo with one solution and all projects so we can reference them in csproj. And we all have same fder structure

No 2) we reference them as nuget package. Usual nuget search first local so if msbuild copy NumSharp nuget package automatically to local cache we are fine. :)

Maybe we have other options?

**Comment by dotChris90** [comment]
Until now i go your option 3.

But we should really consider other solution

**Comment by Oceania2018** [comment]
Submodule is another option.
https://blog.github.com/2016-02-01-working-with-submodules/

**Comment by dotChris90** [comment]
Cool. I was always wondering what this strange folder in ironpython is.

https://github.com/IronLanguages/ironpython3/tree/master/Src

From the blog it's a submodule. Indeed that would be an option.
