### ISSUE TITLE
implement numpy.convolve

### ISSUE THREAD

**Issue by Oceania2018** [Oceania2018/NumSharp#6]
Returns the discrete, linear convolution of two one-dimensional sequences. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.convolve.html

**Comment by dotChris90** [comment]
Pull request started. But for now just the full mode. 

still to do : 

- same mode 
- valid mode 

according to https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.convolve.html

**Comment by Oceania2018** [comment]
@dotChris90 created more functions to be implemented. Please pick up one if you want.

**Comment by dotChris90** [comment]
when pull request is accepted, will close this ticket ;)

**Comment by dotChris90** [comment]
closing it because all 3 modes are implemented ("same", "Full", "valid")

**Comment by dotChris90** [comment]
can not close ticket. :-/ but it can be closed in general.
