### ISSUE TITLE
Rewrite methods so NDArray_Legacy can be finally removed

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#67]
- since now we 0.3 I want to start tidy up little bit 
- I kick out NDArray_legacy since we finally decided to go with the 1D array storage and I do not want to start a 2nd NDArray version 
;)
- I will do it

**Comment by Oceania2018** [comment]
Sounds great.

**Comment by dotChris90** [comment]
Will close because pull request
