### ISSUE TITLE
partial class NDArray<T>

### ISSUE THREAD

**Issue by Oceania2018** [Oceania2018/NumSharp#72]
@dotChris90  Don't know why we need this. Could you give me the use case?

```
public partial class NDArray<T>
{
    public NDArray<T> reshape(params int[] shape)
    {
        return NumSharp.Extensions.NDArrayExtensions.reshape(this, shape);
    }
}
```

**Comment by dotChris90** [comment]
No use case in c#.

Was again for the other languages like powershell or f#.

You can remove the file extensionlinking totally or I do by myself. :)

**Comment by dotChris90** [comment]
Close because class was removed totally in #87

**Comment by Oceania2018** [comment]
New a project in the src folder named `NumSharp.PowerShell`.
