### ISSUE TITLE
implement numpy.mean

### ISSUE THREAD

**Issue by Oceania2018** [Oceania2018/NumSharp#8]
Compute the arithmetic mean along the specified axis.
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.mean.html

**Comment by dotChris90** [comment]
ok - will do this - seems to be easy ;)

**Comment by dotChris90** [comment]
ok - pull request for first implementation of mean 
keep issue open because API is not full implemented (missing multi dimensional stuff)

**Comment by Oceania2018** [comment]
Can you do NumPy.hstack first, other contributor is working on NumPy.mean.
