### ISSUE TITLE
Rewrite Shape class as struct

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#89]
Is there any reason to keep shape as "reference" class? 

If I remember well classes are references by default and structures are not. 
I just think in linear algebra there will be very often the case that we set the shape of one array to a shape of an other array. Since all is done by reference if I change the shape of a array the shape of 2nd arrays shape will change also. 

This is a side effect. So question --> is there any reason for Shape as class?

**Comment by Oceania2018** [comment]
We are used to writing code with classes. If we can prove that `struct` is better than `class`, we can consider using struct.

**Comment by dotChris90** [comment]
Ok - when looked again carefully into the class I changed my mind. The important Lists inside there are all read only. So there is no need to change them because side effects are not possible.
