### ISSUE TITLE
Add Argument check in benchmark test 

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/NumSharp#93]
I just saw that different persons have different priorities on benchmark tests. 

I suggest that we define arguments check - something like "dotnet run -c release LinqTest " or "dotnet run -c release NDArrayPerformance" or something like this. 

Also add a powershell file on root level - so easier to execute this benchmark tests. 

@Oceania2018 if you do not mind I would do this

**Comment by Oceania2018** [comment]
@dotChris90 Please do that.

**Comment by dotChris90** [comment]
close because started now need to be extended by everybody

**Comment by Oceania2018** [comment]
I've looked at the commit. I don't think it's good flexible. Please try to use class reflection feature.
